name: Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies for tests
      id: install_dependencies
      run : sudo apt update && sudo apt-get install -y lcov cmake gcc g++ libclang-dev 

    
    - name: Run Coverage
      id: run_coverage
      run: |
        mkdir build
        cd build
        cmake ${{github.workspace}} -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON
        make
        make test ARGS="-V"
        cd  ../
                
        echo "Creating build/coverage_data directory..."
        mkdir -p build/coverage_data
        
        echo "Copying files to build/coverage_data:"
        find build -type f -name "*.gcda" -exec cp {} build/coverage_data/ \;
        find build -type f -name "*.gcno" -exec cp {} build/coverage_data/ \;

        cd build/coverage_data

        echo "LCOV output to total coverage"
        lcov -b ${{github.workspace}}/src -c -d ${{github.workspace}}/build/coverage_data -o total_coverage.info

        echo "Generate HTMsL"
        genhtml total_coverage_filtered.info --output-directory coverage_report

