name: Coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push.outputs.commit_hash }}

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies for tests
      id: install_dependencies
      run : sudo apt update && sudo apt-get install -y lcov cmake gcc g++ libclang-dev gcovr

    
    - name: Run Coverage
      id: run_coverage
      run: |
        mkdir build
        cd build
        cmake ${{github.workspace}} -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DGCOV_EXECUTABLE=gcov-12
        make
        make test ARGS="-V"
        cd ../
  
    - name: Generate coverage report
      run: |
        pip install --upgrade gcovr
        gcovr --cobertura  --gcov-executable gcov-12 -o ./test/docs/coverage.xml -e "build/_deps/*"        
    
    # - name: Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     filename: ./test/docs/coverage.xml
    #     badge: true
    #     fail_below_min: false
    #     format: markdown
    #     hide_branch_rate: false
    #     hide_complexity: true
    #     indicators: true
    #     output: both
    #     thresholds: '60 80'

    - name: Produce the coverage report
      uses: insightsengineering/coverage-action@v2
      with:
        path: ./test/docs/coverage.xml
        fail: false
        publish: true
        diff: true
        diff-branch: main
        coverage-summary-title: "Code Coverage Summary"

    
    - name: Configure Git
      run: |
        echo "Setting up git configuration..."
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit and push changes
      id: commit-and-push
      uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        file_pattern: '*.xml'

  publish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:

    - name: Check Out the Repo Again
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.update-changelog.outputs.commit_hash }}

