name: Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies for tests
      id: install_dependencies
      run : sudo apt update && sudo apt-get install -y lcov cmake gcc g++ libclang-dev gcovr

    
    - name: Run Coverage
      id: run_coverage
      run: |
        mkdir build
        cd build
        cmake ${{github.workspace}} -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DGCOV_EXECUTABLE=gcov-12
        make
        make test ARGS="-V"
        cd  ../

        mkdir -p coverage
        gcovr --html --gcov-executable gcov-12 -o coverage/coverage_report.html --filter "build/_deps/*"
    
        echo "Setting up git configuration..."
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
    
        echo "Committing and pushing changes..."
        git add coverage
        git commit -m "Update coverage report [skip ci]"
        git push
