name: Coverage

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies for tests
      id: install_dependencies
      run : sudo apt update && sudo apt-get install -y lcov cmake gcc g++ libclang-dev gcovr

    
    - name: Run Coverage
      id: run_coverage
      run: |
        mkdir build
        cd build
        cmake ${{github.workspace}} -DBUILD_PLUGIN_NOOP=ON -DENABLE_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DGCOV_EXECUTABLE=gcov-12
        make
        make test ARGS="-V"
        cd ../

    - name: Copy coverage data
      run: |
        echo "Copying files to build/coverage_data:"
        find build -type f -name "*.gcda" -exec cp {} build/coverage_data/ \;
        find build -type f -name "*.gcno" -exec cp {} build/coverage_data/ \;
  
    - name: Generate coverage report
      run: |
        gcovr --html --gcov-executable gcov-12 -o coverage.html --print-summary -e "build/_deps/*"

    - name: Configure Git
      run: |
        echo "Setting up git configuration..."
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit and push changes
      run: |
          git add coverage.html
          git commit -m "Update coverage report"
          git push origin HEAD:refs/heads/your-feature-branch
