name: Release

on:
  pull_request:
    types:
      - closed

  
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        archconfig: [ x86_64, aarch64, armv7l ]
        build_type: [Debug, Release]
      fail-fast: false

    steps:
    - name: Cleanup previous jobs
      run: |
        echo "Cleaning up previous runs"
        sudo rm -rf ${{ github.workspace }}/*
        sudo rm -rf ${{ github.workspace }}/.??*
    

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Clean-up
      run: sudo rm -rf artifacts build_${{ matrix.build_type }}

  coverage_docs:
      uses: ./.github/workflows/coverage_upload.yml
      needs: [build]
  #